<?php

function mods_h5p_styles_alter(&$styles, $libraries, $mode) {
  if ($mode == 'editor') {
    $styles[] = (object) array(
      // Path relative to drupal root
      'path' => drupal_get_path('module', 'mods') . '/enactCSSmods25.css',
      // Cache buster
      'version' => '?ver=1',
    );
  }
}


function mods_h5p_scripts_alter(&$scripts, $libraries, $mode) {
    $scripts[] = (object) array(
      // Path relative to drupal root
      'path' => drupal_get_path('module', 'mods') . '/JSOverrides.js',
      // Cache buster
      'version' => '?ver=1',
    );
}
